src/CMS.UI/Controllers/StripeController.cs
using System;
using System.Web.Mvc;
using CMS.BL.Entity;
using CMS.Services;
using CMS.Services.Interfaces;
using CMS.Services.Model;
using CMS.UI.Models;

namespace CMS.UI.Controllers
{
    public class StripeController : BaseWebController
    {
        private readonly IDomain _domainService;
        private readonly IECommerce _eCommerceService;
        private readonly IStripe _stripeService;

        public StripeController(IDomain domainService,
            IECommerce ecommerceService,
            IUser userService,
            IWebContent webContentService,
            IStripe stripeService)
            : base(domainService, ecommerceService, userService, webContentService)
        {
            _domainService = domainService;
            _eCommerceService = ecommerceService;
            _stripeService = stripeService;
        }

        [HttpGet]
        #if RELEASE
            [RequireHttps]
        #endif
        public ActionResult Payment(int orderID = 0)
        {
            if (orderID <= 0)
            {
                return RedirectToRoute("Website", new {action = "PaymentError", orderID = orderID.ToString()});
            }

            tbl_Orders order = _eCommerceService.GetOrderByID(orderID);

            if (order == null)
            {
                throw new Exception("No order has been found");
            }

            return View();
        }

        [HttpPost]
        #if RELEASE
            [RequireHttps]
        #endif
        [ValidateAntiForgeryToken]
        public ActionResult Payment(StripeCheckoutViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var apiKey = _domainService.GetSettingsValue(BL.SettingsKey.stripeApiKey, DomainID);
                var result =_stripeService.ProcessPayment(new StripeCheckoutModel
                {
                    CreditCardNumber = viewModel.CreditCardNumber,
                    Cvv = viewModel.Cvv,
                    ExpiryMonth = viewModel.ExpiryMonth,
                    ExpiryYear = viewModel.ExpiryYear,
                    OrderId = viewModel.OrderId
                }, apiKey, DomainID);

                if (!result.IsError)
                {
                    return RedirectToAction("ThankYou", "Website", new { orderID = viewModel.OrderId });
                }

                ModelState.AddModelError("",result.Message);
            }
            return View();
        }
    }
}

src/CMS.UI/Views/Stripe/Payment.cshtml
@model CMS.UI.Models.StripeCheckoutViewModel
@{
    ViewBag.Title = "Stripe Checkout";
}
@section metatags {
    @{Html.RenderPartial("/Views/Partials/MetaTags.cshtml", new CMS.UI.Models.MetadataModel());}
}
@section styles {
    @Styles.Render("~/Content/themes/base/ui.css")
}
@section scripts {
    @Scripts.Render("~/bundles/jqueryUI")
}
@section sidebar {
    @{
        Html.RenderPartial("../Partials/SearchPanel");
        Html.RenderAction("ContactUsPartial", "Website");
    }
}

<h1>Stripe Checkout</h1>

<div id="StripeCheckout">

    @using (Html.BeginForm("Payment", "Stripe"))
    {
        <div class="row">
            <div class="col-sm-5">
                @Html.AntiForgeryToken()
                <div>@Html.ValidationSummary(true)</div>
                <div class="form-group">
                    @Html.LabelFor(m => m.CreditCardNumber)
                    @Html.TextBoxFor(m => m.CreditCardNumber, new { @class = "form-control", maxlength="16", data_stripe="number"})
                    @Html.ValidationMessageFor(m => m.CreditCardNumber)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Cvv)
                    @Html.TextBoxFor(m => m.Cvv, new { @class = "form-control", maxlength = "4", data_stripe = "cvc" })
                    @Html.ValidationMessageFor(m => m.Cvv)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ExpiryMonth)
                    @Html.TextBoxFor(m => m.ExpiryMonth, new { @class = "form-control", maxlength = "2", data_stripe = "exp-month" })
                    @Html.ValidationMessageFor(m => m.ExpiryMonth)
                </div>
                
                <div class="form-group">
                    @Html.LabelFor(m => m.ExpiryYear)
                    @Html.TextBoxFor(m => m.ExpiryYear, new { @class = "form-control", maxlength = "4", data_stripe = "exp-year" })
                    @Html.ValidationMessageFor(m => m.ExpiryYear)
                </div>
            </div>
        </div>
        
        <div class="form-group">
            @Html.HiddenFor(m => m.OrderId)
            <input type="submit" class="btn btn-warning pull-right" value="Proceed" />
        </div>
        
    }

</div>