src/CMS.UI/Models/POI/POICategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CMS.UI.Models
{
    public class POICategoryModel
    {
        public int POICategoryID { get; set; }
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }
        [Display(Name = "Is Live")]
        public bool IsLive { get; set; }
    }
}

src/CMS.UI/Models/POI/POIFileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CMS.UI.Models
{
    public class POIFileModel
    {
        public int FileID { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public string Path { get; set; }
    }
}

src/CMS.UI/Models/POI/POIModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace CMS.UI.Models
{
    public class POIModel
    {
        public POIModel()
        {
            this.TagsIDs = new int[0];
        }

        public int POIID { get; set; }
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }
        public string Description { get; set; }
        [Display(Name = "Telephone Number")]
        public string Phone { get; set; }
        [Display(Name = "Category")]
        [Required(ErrorMessage = "Category is required")]
        [Range(1, Int16.MaxValue, ErrorMessage = "Category is required")]
        public int CategoryID { get; set; }
        [Required(ErrorMessage = "Latitude is required")]
        public string Latitude { get; set; }
        [Required(ErrorMessage = "Longitude is required")]
        public string Longitude { get; set; }
        [Display(Name = "Page Linked With POI")]
        public int? SitemapID { get; set; }
        [Display(Name = "Domain")]
        public int DomainID { get; set; }

        public int AddressID { get; set; }
        [Display(Name="Address 1")]
        [Required(ErrorMessage = "Address 1 is required")]
        public string Address1 { get; set; }
        [Display(Name = "Address 2")]
        public string Address2 { get; set; }
        [Display(Name = "Address 3")]
        public string Address3 { get; set; }
        [Required(ErrorMessage = "Town is required")]
        public string Town { get; set; }
        [Required(ErrorMessage = "Postcode is required")]
        public string Postcode { get; set; }
        public string County { get; set; }
        [Required(ErrorMessage = "Country is required")]
        public string Country { get; set; }

        public int[] TagsIDs { get; set; }
    }
}

src/CMS.UI/Models/POI/POITagModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CMS.UI.Models
{
    public class POITagModel
    {
        public int POITagID { get; set; }
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }
        [Display(Name = "POI Tags Group")]
        [Required(ErrorMessage = "Title is required")]
        [Range(1, Int16.MaxValue, ErrorMessage = "Title is required")]
        public int POITagsGroupID { get; set; }
    }
}

src/CMS.UI/Models/POI/POITagsGroupModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace CMS.UI.Models
{
    public class POITagsGroupModel
    {
        public int POITagsGroupID { get; set; }
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }
        public virtual List<SelectListItem> POITags { get; set; }
    }
}

src/CMS.UI/Models/POI/POIWebModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CMS.UI.Models
{
    public class POIWebModel
    {
        public int POIID { get; set; }
        public string Title { get; set; }
        public string CategoryTitle { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Phone { get; set; }
    }
}

src/CMS.UI/Models/POI/POIWebTagsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.UI.Models
{
    public class POIWebFilterModel
    {
        public bool IsColumn1 { get; set; }
        public bool IsColumn2 { get; set; }

        public POIWebTagGroupModel Column1 { get; set; }
        public POIWebTagGroupModel Column2 { get; set; }
    }

    public class POIWebTagGroupModel
    {
        public string Label { get; set; }
        public SelectList Tags { get; set; }
    }
}

src/CMS.UI/Controllers/WebsiteController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

using CMS.BL;
using CMS.BL.Entity;
using CMS.Services;
using CMS.Services.Extensions;
using CMS.UI.Common;
using CMS.UI.Models;
using CMS.UI.Security;
using CMS.Utils;
using CMS.Utils.Cryptography;
using Recaptcha.Web;
using Recaptcha.Web.Mvc;
using CMS.BL.Comparers;
using CMS.Utils.Diagnostics;
using CMS.Utils.Extension;
using Newtonsoft.Json;

namespace CMS.UI.Controllers
{
    [Authentication]
    [CookieConsent]
    public class WebsiteController : BaseWebController
    {
        private readonly IDomain DomainService;
        private readonly IWebContent WebContentService;
        private readonly IECommerce ECommerceService;
        private readonly IWebPages WebPagesService;
        private readonly IUser UserService;
        private readonly IPOI POIService;
        private readonly ITemplate TemplateService;
        private readonly IPortfolio PortfolioService;
        private readonly IGallery GalleryService;

        public WebsiteController(IDomain domainService,
            IWebContent webContentService,
            IECommerce ecommerceService,
            IWebPages webPagesService,
            IUser userService,
            IPOI poiService,
            ITemplate templateService,
            IPortfolio portfolioService,
            IGallery galleryService)
            : base(domainService, ecommerceService, userService, webContentService)
        {
            this.DomainService = domainService;
            this.WebContentService = webContentService;
            this.ECommerceService = ecommerceService;
            this.WebPagesService = webPagesService;
            this.UserService = userService;
            this.POIService = poiService;
            this.TemplateService = templateService;
            this.PortfolioService = portfolioService;
            this.GalleryService = galleryService;

        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Content(int sectionID = 0, int contentID = 0)
        {
            sectionID = Request.Url.LocalPath == "/" && this.Domain != null ? this.Domain.DO_HomePageID : sectionID;
            var user = this.AdminUser != null ? this.AdminUser.IsAdmn : false;
            tbl_Content content = WebContentService.GetContentBySitemapUrl(Request.Url.LocalPath, this.DomainID, sectionID, contentID, user, this.Domain.DO_HomePageID);

            if (content == null)
            {
                content = WebContentService.GetContentByRedirectUrl(Request.Url.LocalPath, this.DomainID, contentID);
                if (content != null)
                    return RedirectPermanent(content.tbl_SiteMap.SM_URL);
            }

            if (content == null)
                throw new HttpException(404, "Page Not Found");
                //return null;

            //check for post data
            if (Request.HttpMethod == "POST") //possible form submission
            {
                string postedFormID = Request.Form["formid"];
                int formID = 0;
                Int32.TryParse(postedFormID, out formID);
                if (formID > 0)
                {
                    tbl_Form form = WebPagesService.GetFormByID(formID);
                    if (form != null)
                    {
                        this.ViewBag.Tracking = form.F_Tracking;
                    }
                }
            }

            this.ViewBag.IsHomePage = (content.C_TableLinkID == this.Domain.DO_HomePageID);

            if (Request.Url.LocalPath == "/" && content.tbl_SiteMap.SM_IsPredefined)
            {
                switch (content.tbl_SiteMap.SM_TypeID.GetValueOrDefault(0))
                {
                    case (int)SiteMapType.News:
                        return Blog(String.Empty, String.Empty, String.Empty);
                    case (int)SiteMapType.ProductShop:
                        return ProdCategories();
                    case (int)SiteMapType.Portfolio:
                        return Portfolio();
                    case (int)SiteMapType.Gallery:
                        return Gallery();
                    case (int)SiteMapType.EventShop:
                        return EventsCategories();
                    case (int)SiteMapType.Sitemap:
                        return Sitemap();
                    case (int)SiteMapType.Testimonials:
                        return Testimonials();
                    case (int)SiteMapType.Subscribe:
                        return Subscribe();
                    case (int)SiteMapType.Donation:
                        return DonationCategories();
                    case (int)SiteMapType.PointsOfInterest:
                        return POIs();
                }
            }

            if (content.tbl_SiteMap.SM_TypeID != null && content.tbl_SiteMap.SM_TypeID != (int)SiteMapType.Sitemap && content.tbl_SiteMap.SM_TypeID != (int)SiteMapType.ContactUs)
                throw new HttpException(404, "Page Not Found");

            ContentModel contentModel = ContentModelFactory(content);
            this.ViewBag.Title = content.C_Title;
            this.ViewBag.PageID = contentModel.Content.tbl_SiteMap.SiteMapID;

            this.ViewBag.DynamicLayout = GetLayout(content, WebPagesService);
            return View(contentModel);
        }

        [AllowAnonymous]
        public ActionResult Breadcrumbs(string url = "")
        {
            url = String.IsNullOrEmpty(url) ? this.Request.Url.AbsolutePath : url;
            ViewBag.CompanyName = this.Domain != null ? this.Domain.DO_CompanyName : string.Empty;
            return PartialView("Breadcrumbs", FindBreadcrumbByUrl(url, GetMenuAllOrdered()));
        }

        [AllowAnonymous]
        public ActionResult Menu()
        {
            return PartialView("Menu", GetMenuOrdered(true, false, false, false, true, false));
        }

        [AllowAnonymous]
        public ActionResult SubMenu(int sitemapID = 0)
        {
            return PartialView("SubMenu", GetSubMenuOrdered(true, false, false, sitemapID, false, true, false));
        }

        [AllowAnonymous]
        public ActionResult GetTweets(int count = 3)
        {
            List<string> tweets = null;
            var domain = this.Domain;
            if (domain != null)
            {
                TweetManager tweet = new TweetManager(domain.DO_TwitterToken, domain.DO_TwitterSecret, domain.DO_ConsumerKey, domain.DO_ConsumerSecret);
                tweets = tweet.GetLatestTweets(count);
            }
            return PartialView("/Views/Partials/GetTweets.cshtml", tweets);
        }

        [AllowAnonymous]
        public ActionResult Footer()
        {
            var paymentModel = ECommerceService.GetAllPaymentsDomain(this.DomainID).Where(s => !String.IsNullOrWhiteSpace(s.PD_Logo))
                .Select(m => new PaymentLogoModel
            {
                Code = m.tbl_PaymentType.PT_Code,
                Name = m.tbl_PaymentType.PT_Name,
                FilePath = String.Format("/{0}/{1}/{2}", SettingsManager.Payment.PaymentLogosPath.Trim('/'), this.DomainID, m.PD_Logo)
            }).ToList();
            var template = TemplateService.GetLive();
            ViewBag.CompanyName = this.Domain != null ? this.Domain.DO_CompanyName : string.Empty;
            ViewBag.Telephone = this.Domain != null ? this.Domain.DO_CompanyTelephone : string.Empty;
            ViewBag.Address = this.Domain != null ? this.Domain.DO_CompanyAddress : string.Empty;
            ViewBag.Email = this.Domain != null ? this.Domain.DO_Email: string.Empty;
            return PartialView("Footer",
                new FooterModel
                {
                    WebsiteMenu = GetMenuOrdered(false, true, false),
                    PaymentMethods = paymentModel,
                    FooterContent = template != null ? template.T_Footer : String.Empty,
                    UseTemplate = template != null ? template.T_UseFooter : false
                });
        }

        [AllowAnonymous]
        public ActionResult Sitemap()
        {
            this.ViewBag.SitemapPage = WebContentService.GetContentBySitemapUrl(WebContentService.GetSitemapUrlByType(SiteMapType.Sitemap, this.DomainID).TrimEnd('/'), this.DomainID);
            return View("Sitemap", GetMenuOrdered(false, false, true, true, true, true));
        }

        [AllowAnonymous]
        public ActionResult WebsiteUrls(string time)
        {
            var list = CreateElements(GetMenuAllOrdered()).OrderBy<LinkListItem, string>(x => x.title).ToList();
            return PartialView("UrlsList", list);
        }

        [AllowAnonymous]
        public ActionResult CustomEditorObjects(int currentDomainID, string selector)
        {
            if (currentDomainID == 0)
            {
                currentDomainID = DomainID;
            }
            return Json(new
            {
                selector = selector,
                // tinyMCE: link_list
                link_list = CreateElements(GetMenuOrdered(false, false, true)).OrderBy(x => x.title).ToArray(),
                // tinyMCE: customform_list
                customForms = WebPagesService.GetAllForms().OrderBy(f => f.F_DomainID).ThenBy(f => f.F_Name).Select(f => new LinkListItem
            {
                title = String.Format("{0} ({1})", f.F_Name, f.tbl_Domains.DO_Domain),
                value = f.FormID.ToString()
            }).ToArray()
            }, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public ActionResult XMLSitemap()
        {
            if (!Directory.Exists(Server.MapPath(SettingsManager.Sitemap.Folder)))
                Directory.CreateDirectory(Server.MapPath(SettingsManager.Sitemap.Folder));

src/CMS.UI/Views/Website/Basket.cshtml
@{
    ViewBag.Title = "Shopping Basket";
}
@section metatags {
    @{Html.RenderPartial("/Views/Partials/MetaTags.cshtml", new CMS.UI.Models.MetadataModel());}
}
@section scripts {
    @Scripts.Render("~/bundles/otherLibs")
    @Scripts.Render("~/bundles/basketManager")
}
@section sidebar {
    @{
        Html.RenderPartial("../Partials/SearchPanel");
        Html.RenderAction("ContactUsPartial", "Website");
    }
}
<div id="Basket" class="basket"
     data-adddiscount-url="@Url.Action("AddDiscount", "Website")"
     data-canproceedtocheckout-url="@Url.Action("CanProceedToCheckout", "Website")"
     data-getavailablepostage-url="@Url.Action("GetAvailablePostage", "Website")"
     data-getbasketdata-url="@Url.Action("GetBasketData", "Website")"
     data-getcountrieslist-url="@Url.Action("GetCountries", "Website")"
     data-getprices-url="@Url.Action("GetBasketPrices", "Website")"
     data-proceed-url="@Url.RouteUrl("Checkout")"
     data-removediscount-url="@Url.Action("RemoveDiscount", "Website")"
     data-removefrombasket-url="@Url.Action("RemoveFromBasket", "Website")"
     data-updatebasketpostage-url="@Url.Action("UpdateBasketPostage", "Website")"
     data-updateproductamount-url="@Url.Action("UpdateProductAmount", "Website")">
    <h1>Shopping Basket</h1>
    <div data-bind="visible: !isBasket()">
        <p>Your basket is currently empty</p>
    </div>
    <div data-bind="visible: isBasket">
        @Html.Partial("~/Views/Partials/PromotionalCode.cshtml")
        <div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Item</th>
                        <th>Price</th>
                        @if (ViewBag.DisplayTax)
                        {
                            <th>VAT</th>
                        }
                        <th class="border">Quantity</th>
                        <th>Sub Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody data-bind="foreach: basketItems">
                    <tr data-bind="attr: { 'data-contentID': BasketContentID }">
                        <td><span data-bind="text: CategoryTitle"></span></td>
                        <td>
                            <span data-bind="text: ProductTitle"></span>
                            <br />
                            <span data-bind="html: Attributes"></span>
                        </td>
                        <td><span data-bind="text: ItemSinglePrice"></span></td>
                        @if (ViewBag.DisplayTax)
                        {
                            <td><span data-bind="text: TaxValue"></span></td> }
                        <td class="border">
                            <div class="row">
                                <div class="col-sm-6">
                                    <input name="tbAmount" type="number" class="form-control" data-bind="value: Quantity, event: { change: $root.onAmountChanged }, attr: { min: Min, max: Max }" />
                                </div>
                            </div>
                        </td>
                        <td><span data-bind="text: ItemPrice"></span></td>
                        <td>
                            <button name="btnRemove" class="btn btn-danger" data-bind="click: $root.onRemoveItem">Remove</button>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr data-bind="visible: isDiscount">

                        <td class="border text-right" colspan="@(ViewBag.DisplayTax ? "5" : "4")"><b>Discount</b></td>
                        <td colspan="2">
                            - <span data-bind="text: discountAmount"></span>
                        </td>
                    </tr>
                    <tr data-bind="visible: isDeliverable">

                        <td class="border text-right" colspan="@(ViewBag.DisplayTax ? "5" : "4")"><b>Select Delivery Country</b></td>
                        <td colspan="2">
                            <!-- ko ifnot: isSingleCountry -->
                            <select class="basketFooterInput" data-bind="options: countries, optionsText: 'Text', optionsValue: 'Value', value: countryID"></select>
                            <!-- /ko -->
                            <!-- ko if: isSingleCountry -->
                            <span data-bind="text: countries()[1].Text"></span>
                            <!-- /ko -->
                        </td>
                    </tr>
                    <tr data-bind="visible: isDeliverable">

                        <td class="border text-right" colspan="@(ViewBag.DisplayTax ? "5" : "4")"><b>Select Delivery Option</b></td>
                        <td colspan="2">
                            <!-- ko ifnot: isSinglePostage -->
                            <select class="basketFooterInput" data-bind="options: postages, optionsText: 'Text', optionsValue: 'Value', value: postageID" class="form-control"></select>
                            <!-- /ko -->
                            <!-- ko if: isSinglePostage -->
                            <span data-bind="text: postages()[1].Text"></span>
                            <!-- /ko -->
                        </td>
                    </tr>
                    <tr data-bind="visible: isDeliverable">

                        <td class="border text-right" colspan="@(ViewBag.DisplayTax ? "5" : "4")"><b>Delivery Cost</b></td>
                        <td colspan="2">
                            <span data-bind="text: deliveryCost"></span>
                        </td>
                    </tr>
                    <tr>

                        <td class="border text-right" colspan="@(ViewBag.DisplayTax ? "5" : "4")"><b>EU Member</b></td>
                        <td colspan="2">
                            <input type="text" class="basketFooterInput form-control" placeholder="EU VAT Number" data-bind="value: euVAT" />
                        </td>
                    </tr>
                    <tr>
                        <td class="border text-right" colspan="@(ViewBag.DisplayTax ? "5" : "4")"><b>Total Tax</b></td>
                        <td colspan="2">
                            <span data-bind="text: totalTax"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="border text-right" colspan="@(ViewBag.DisplayTax ? "5" : "4")"><h3>Total</h3></td>
                        <td colspan="2">
                            <h3 data-bind="text: totalPrice"></h3>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
    <div class="buttons pull-right">
        <a href="/" class="btn btn-default">Continue Shopping</a>
        @*@if ((bool)this.ViewBag.ProductSaleEnabled)
            {
                <a href="@ViewBag.ProductUrl" class="btnViolet small">Continue Shopping For
                    Products</a>
            }
            @if ((bool)this.ViewBag.EventSaleEnabled)
            {
                <a href="@ViewBag.EventUrl" class="btnViolet small">Continue Shopping For
                    Events</a>
            }*@
        <a href="#" class="btn btn-warning" data-bind="click: onProceed, visible: isBasket">Proceed to checkout</a>
    </div>
</div>

src/CMS.UI/Views/Website/CustomerGallery.cshtml
@model CMS.BL.Entity.tbl_Gallery

@{
    ViewBag.Title = "Gallery";
}

@section metatags {
    @{Html.RenderPartial("/Views/Partials/MetaTags.cshtml", new CMS.UI.Models.MetadataModel());}
}
@section sidebar {
    @{
        Html.RenderPartial("../Partials/SearchPanel");
        Html.RenderAction("ContactUsPartial", "Website");
    }
}

<h2>@Model.G_Title</h2>
@foreach(CMS.BL.Entity.tbl_GalleryImage image in Model.tbl_GalleryImage)
{
        <img src="@Html.ImageProvider(CMS.BL.ImageVersionName.galleryThumb, @image.tbl_Image.I_Thumb,String.Empty)" alt="@image.tbl_Image.I_Description" />
}

src/CMS.UI/Views/Website/DisplayCustomerAccount.cshtml
@model CMS.UI.Models.CustomerModel
@{
    ViewBag.Title = "Your Account";
}
@section metatags {
    @{Html.RenderPartial("/Views/Partials/MetaTags.cshtml", new CMS.UI.Models.MetadataModel());}
}
@section sidebar {
    @{
        Html.RenderPartial("../Partials/SearchPanel");
        Html.RenderAction("ContactUsPartial", "Website");
    }
}
<h1>Your Account</h1>

@if (Model.galleries != null)
{
    foreach (CMS.BL.Entity.tbl_Gallery gallery in Model.galleries)
    {
        <h2>@gallery.G_Title</h2>
        <img src="@Html.ImageProvider(CMS.BL.ImageVersionName.galleryThumb, gallery.tbl_GalleryImage.FirstOrDefault().tbl_Image.I_Thumb,String.Empty)" alt="@gallery.tbl_GalleryImage.FirstOrDefault().tbl_Image.I_Description" />
        @Html.ActionLink(linkText: "View Gallery", actionName: "CustomerGallery", controllerName: "Website", routeValues: new { galleryID = gallery.GalleryID }, htmlAttributes:new { })
    }
}

<div class="addressLabel">
    <div>
        @Html.LabelFor(m => m.UserName)
        @Html.DisplayFor(m => m.UserName)
    </div>
    <div>
        @Html.LabelFor(m => m.Email)
        @Html.DisplayFor(m => m.Email)
    </div>
    <div>
        @Html.LabelFor(m => m.Phone)
        @Html.DisplayFor(m => m.Phone)
    </div>
</div>
<h2>Address Book</h2>
<h3>@Html.RouteLink("Add new address", "addAddress", null, new { @class = "button" })</h3>
@foreach (var item in Model.addresses)
{
    <fieldset class="addressform">
        <legend class="hidden"></legend>
        <ul>
            <li>@String.Format("{0} {1} {2}", item.A_Title, item.A_FirstName, item.A_Surname)</li>
            <li>@item.A_Line1</li>
            <li>@item.A_Line2</li>
            <li>@item.A_Line3</li>
            <li>@item.A_Town </li>
            <li>@item.A_County</li>
            <li>@item.A_Postcode</li>
            <li>@item.A_Country</li>
        </ul>
        <div class="bottom">
            @Html.RouteLink("Edit", "addAddress", new { id = @item.AddressID }, new { @class = "button" })
            @Html.RouteLink("Delete", "deleteAddress", new { addressID = @item.AddressID }, new { @class = "button", onclick = "return confirm('Are you sure you want to delete this address?') ?  true :  false;" })
        </div>
    </fieldset>
}

src/CMS.UI/Views/Website/EditCustomerAccount.cshtml
@model CMS.UI.Models.EditCustomerModel
@{
    ViewBag.Title = "Edit My Details";
}
@section metatags {
    @{Html.RenderPartial("/Views/Partials/MetaTags.cshtml", new CMS.UI.Models.MetadataModel());}
}
@section sidebar {
    @{
        Html.RenderPartial("../Partials/SearchPanel");
        Html.RenderAction("ContactUsPartial", "Website");
    }
}
<h1>
    Edit My Details
</h1>
<form id="LoginForm" class="webForm" method="post">
    <div class="noLabel">
        @Html.ValidationSummary(true)
    </div>
    <div>
        @Html.LabelFor(model => model.Title)
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
    </div>
    <div>
        @Html.LabelFor(model => model.FirstName)
        @Html.EditorFor(model => model.FirstName)
        @Html.ValidationMessageFor(model => model.FirstName)
    </div>
    <div>
        @Html.LabelFor(model => model.Surname)
        @Html.EditorFor(model => model.Surname)
        @Html.ValidationMessageFor(model => model.Surname)
    </div>
    <div>
        @Html.LabelFor(model => model.Email)
        @Html.EditorFor(model => model.Email)
        @Html.ValidationMessageFor(model => model.Email)
    </div>
    <div>
        @Html.LabelFor(model => model.Phone)
        @Html.EditorFor(model => model.Phone)
        @Html.ValidationMessageFor(model => model.Phone)
    </div>
    @if (ViewBag.SubscriptionEnabled ?? false)
    {
        <div>
            @Html.LabelFor(model => model.SubscribeNewsletter)
            @Html.EditorFor(model => model.SubscribeNewsletter)
        </div>
    }
    <div>
        @Html.LabelFor(model => model.DetailsFor3rdParties)
        @Html.EditorFor(model => model.DetailsFor3rdParties)
    </div>
    <div class="noLabel">
        If you do not wish to change your password then you can leave the following fields
        blank.
    </div>
    <div>
        @Html.LabelFor(model => model.CurrentPassword)
        @Html.PasswordFor(model => model.CurrentPassword)
        @Html.ValidationMessageFor(model => model.CurrentPassword)
    </div>
    <div>
        @Html.LabelFor(model => model.Password)
        @Html.PasswordFor(model => model.Password)
        @Html.ValidationMessageFor(model => model.Password)
    </div>
    <div>
        @Html.LabelFor(model => model.ConfirmPassword)
        @Html.PasswordFor(model => model.ConfirmPassword)
        @Html.ValidationMessageFor(model => model.ConfirmPassword)
    </div>
    <div class="noLabel">
        <input type="submit" value="Save" />
    </div>
</form>

src/CMS.UI/Views/Website/ForgottenPassword.cshtml
@model CMS.UI.Models.LoginModel
@{
    ViewBag.Title = "Forgotten Password";
}
@section metatags {
    @{Html.RenderPartial("/Views/Partials/MetaTags.cshtml", new CMS.UI.Models.MetadataModel());}
}
@section sidebar {
    @{
        Html.RenderPartial("../Partials/SearchPanel");
        Html.RenderAction("ContactUsPartial", "Website");
    }
}
<form method="POST" class="webForm">
    <h1>Password Reset</h1>
    @if (!(bool)this.ViewBag.MailSent)
    {
        <div>
            Please enter your registered email address below and click <b>"Reset Password"</b>. Your password will be reset and emailed to you.
        </div>
        <div>
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email)
        </div>
        <div class="noLabel">
            @Html.ValidationSummary(false)
        </div>
        <div class="noLabel">
            <input type="submit" value="Reset Password" />
        </div>
    }
    else
    {
        <div>
            Your new password has been sent to your registered Email address. Please allow up to
            an hour for the email to arrive.
        </div>
    }
    <div class="noLabel"><a href="@Url.RouteUrl("Login")">Go to Login »</a> </div>
</form>